/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testgles2_GLUtils */

#ifndef _Included_com_example_testgles2_GLUtils
#define _Included_com_example_testgles2_GLUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testgles2_GLUtils
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testgles2_GLUtils_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testgles2_GLUtils
 * Method:    reshape
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_testgles2_GLUtils_reshape
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_testgles2_GLUtils
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testgles2_GLUtils_display
  (JNIEnv *, jclass);

/*
 * Class:     com_example_testgles2_GLUtils
 * Method:    update
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_com_example_testgles2_GLUtils_update
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     com_example_testgles2_GLUtils
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testgles2_GLUtils_reset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
